
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-odoo_prod}
      POSTGRES_USER: ${POSTGRES_USER:-odoo_prod}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo_prod}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - odoo-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  odoo:
    build: 
      context: .
      target: production
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "${ODOO_PORT:-8069}:8069"
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_logs:/var/log/odoo
      - ./addons:/opt/odoo/custom-addons:ro
      - ./config/odoo.prod.conf:/etc/odoo/odoo.conf:ro
    environment:
      - ODOO_DB_HOST=postgres
      - ODOO_DB_USER=${POSTGRES_USER:-odoo_prod}
      - ODOO_DB_PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_DB_NAME=${POSTGRES_DB:-odoo_prod}
      - ODOO_ADMIN_PASSWORD=${ODOO_ADMIN_PASSWORD}
    networks:
      - odoo-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  nginx:
    image: nginx:alpine
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - odoo
    networks:
      - odoo-network
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local
  odoo_logs:
    driver: local

networks:
  odoo-network:
    driver: bridge
=======
version: '3.8'

# Docker Compose para producción de Odoo 18.0
# Configuración con Nginx reverse proxy y SSL

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: odoo_prod_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: ${DB_USER:-odoo}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-odoo_secure_password}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - odoo_internal
    # No exponemos el puerto externamente por seguridad

  # Odoo Application
  odoo:
    image: odoo:18.0
    container_name: odoo_prod_app
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=${DB_USER:-odoo}
      - PASSWORD=${DB_PASSWORD:-odoo_secure_password}
      - POSTGRES_DB=${DB_NAME:-postgres}
    volumes:
      - odoo_prod_data:/var/lib/odoo
      - odoo_prod_logs:/var/log/odoo
      - ./config/odoo.prod.conf:/etc/odoo/odoo.conf:ro
    restart: unless-stopped
    networks:
      - odoo_internal
    # No exponemos puertos directamente, solo a través de Nginx

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: odoo_nginx
    depends_on:
      - odoo
    ports:
      - "80:80"      # HTTP (redirigido a HTTPS)
      - "443:443"    # HTTPS
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    networks:
      - odoo_internal
      - web

  # Certbot para SSL automático (Let's Encrypt)
  certbot:
    image: certbot/certbot
    container_name: odoo_certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/certbot-webroot:/var/www/certbot
    command: certonly --webroot -w /var/www/certbot --force-renewal --email ${SSL_EMAIL} -d ${DOMAIN} --agree-tos --no-eff-email
    depends_on:
      - nginx
    networks:
      - web

volumes:
  postgres_prod_data:
    driver: local
  odoo_prod_data:
    driver: local
  odoo_prod_logs:
    driver: local
  nginx_logs:
    driver: local

networks:
  odoo_internal:
    driver: bridge
    internal: true  # Red interna, no acceso directo desde internet
  web:
    driver: bridge  # Red para acceso web
