version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: odoo_postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - odoo_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Odoo Application
  odoo:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: odoo_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo_prod
    volumes:
      - odoo_data:/opt/odoo/data
      - odoo_logs:/opt/odoo/logs
      - odoo_addons:/opt/odoo/addons
      - ./config:/opt/odoo/config:ro
    ports:
      - "8069:8069"
      - "8071:8071"
      - "8072:8072"
    restart: unless-stopped
    networks:
      - odoo_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  # Nginx Reverse Proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: odoo_nginx
    depends_on:
      - odoo
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - odoo_network

  # Redis para sesiones (opcional)
  redis:
    image: redis:7-alpine
    container_name: odoo_redis
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - odoo_network

volumes:
  postgres_data:
    driver: local
  odoo_data:
    driver: local
  odoo_logs:
    driver: local
  odoo_addons:
    driver: local
  redis_data:
    driver: local

networks:
  odoo_network:
    driver: bridge
