# Docker Compose Simple para desarrollo de Odoo 18.0
# Configuración mínima para pruebas rápidas

services:
  # PostgreSQL Database
  db:
    image: postgres:14-alpine
    container_name: odoo_simple_db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_simple_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5434:5432"
    restart: unless-stopped
    networks:
      - odoo_simple_network

  # Odoo Development - Version Simple
  odoo:
    image: odoo:18.0
    container_name: odoo_simple_app
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - DB_NAME=odoo_simple
    volumes:
      - ./config:/opt/odoo/config:rw
      - odoo_simple_data:/opt/odoo/data
    ports:
      - "8070:8069"
    restart: unless-stopped
    networks:
      - odoo_simple_network

volumes:
  postgres_simple_data:
    driver: local
  odoo_simple_data:
    driver: local

networks:
  odoo_simple_network:
    driver: bridge
